### ISSUE TITLE
Add a volunteer page

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#102]
People have contacted us about volunteer opportunities per our About page, but it would be great if we could elaborate on our open positions in more detail. Whether it's implemented as a link to a google form application or a page with some permanent descriptions, it would be cool either way to see something along these lines.

**Comment by evykassirer** [comment]
@arshiamufti this is the thing you're doing right? :)

**Comment by arshiamufti** [comment]
Yep.

**Comment by evykassirer** [comment]
done!!
