### ISSUE TITLE
Constitution Improvements meta-issue #119: Chair term limit

### ISSUE THREAD

**Issue by fboxwala** [wics-uw/website#123]
Making an issue for this because I think it requires some discussion. I'm of the opinion that there should be a term limit but higher than two. Three would be acceptable to me.

A two-consecutive term limit seems unnecessary because a chair who has already served a term is chair has experience and is potentially the best candidate to be chair again. Furthermore, it can be hard to find anyone to do the job (see Fall15) so having more restrictions seems like a bad idea.

@wics-uw/contributors opinions and suggestions.

**Comment by evykassirer** [comment]
maybe we could say that if someone has chaired 3 times, it is preferred that someone else chairs, unless no one is interested?
I want to make sure that people who are interested feel that they can speak up and take over from someone who has been strongly associated with the role

**Comment by fboxwala** [comment]
So are you saying we do something like this:

There is no limit on the number of terms that one person may serve as chair, however preference in the evaluation process will be given to those candidates who have served 2 or fewer terms in the position.

Or like this:

No one person may serve as chair for more than 5 total terms. Furthermore, in the evaluation process, candidates who have served 2 or fewer terms will be given preference over those who have served 3 or more.

**Comment by evykassirer** [comment]
I'm leaning towards first one with "strong preference"
to cover the case where we have trouble bringing in people who want to chair

**Comment by fboxwala** [comment]
Okay @wics-uw/contributors how does everyone feel about this?

There is no limit on the number of terms that one person may serve as chair, however _strong preference_ in the evaluation process will be given to those candidates who have served 2 or fewer terms in the position.

**Comment by ehashman** [comment]
I think the only limit there should be is that an individual cannot serve three consecutive terms as Chair. This allows for two in a row, but doesn't limit total number of terms as chair (I don't know of any club who puts those kinds of limits on exec).

I mean, the chair is selected by the committee, so if there is a problem with their chairing, presumably they wouldn't be selected again. I don't like the idea that being chair is a special experience that needs to be shared amongst the committee, and thus inexperienced people interested in trying it should get priority over experienced ones. If the person running believes that makes more sense than their own service, then surely they won't nominate themself.

**Comment by fboxwala** [comment]
So currently we have:

_There is no limit on the number of terms that one person may serve as chair, however strong preference in the evaluation process will be given to those candidates who have served 2 or fewer terms in the position._

and:

_No individual may serve as chair consecutively for more than 2 terms._
Which I think is also the language we have in there right now. 

I think it should be the second one as well. I don't think language in the constitution will be what scares people off from trying out for chair, and this is one position in which experience is going to be your best asset.

@wics-uw/contributors some thoughts from lots of people is better than lots of thoughts from some people.

**Comment by ehashman** [comment]
I claim there is a more simple solution. I think we should reduce the limit for consecutive terms that a member can serve to two, and then we can remove the special case for chair.

**Comment by evykassirer** [comment]
But then people who have school coop (on campus) school can't be on committee for the
terms they're around :/

**Comment by fboxwala** [comment]
I think that's the point, that we don't want one person having a permanent seat on committee for twelve months.

**Comment by ehashman** [comment]
Yeah, exactly. I really want to discourage people from being on the committee continuously for too long, especially while on co-op. Co-op should be a time for individuals to get new, non-school experience. I don't want to see a bunch of WiCS volunteers doing three terms of committee service in a study/co-op/study sequence. One thing I was guilty of as a student was trying to stay in the Waterloo area for my more junior co-ops in order to be closer to campus and stay involved. The tradeoff was not going abroad for co-op and getting valuable experience, and I think that is harmful. It also can lead to burnout.

Additionally, given how many returning committee members we have to work with, if we let them all automatically stay on the committee for an entire year, I don't think this is fair to new volunteers.

**Comment by evykassirer** [comment]
I'm convinced :)
++

**Comment by ehashman** [comment]
Resolved by #136
