### ISSUE TITLE
Constitution Improvements meta-issue 119: too many qualified applicants

### ISSUE THREAD

**Issue by fboxwala** [wics-uw/website#125]
When we have too many qualified applicants who are new, I think these decisions can still be made through the normal interview/evaluation process.

When we have too many qualified returning members, the decision for who gets to be on committee should be escalated, because clearly we can't be objective about ourselves. What I put in for this situation was that everyone should go through the regular interview/application process and be evaluated by the serving Director of WiCS.

Thoughts? @wics-uw/contributors

**Comment by ehashman** [comment]
I guess my issue is one of fairness to new committee members. Let me sketch out some hypothetical scenarios. We note the maximum number of committee members is 10.

**Scenario 1:** 6 qualified new members, 5 qualified returning members.
- Possible outcome: all members are referred to WiCS Chair for selection
- Possible outcome: a returning member self-selects out
- Possible outcome: current committee disqualifies one of the new members

**Scenario 2:** 3 qualified new members, 8 qualified returning members.
- Possible outcome: returning members are referred to WiCS Chair for selection, who will pick 7
- Possible outcome: a returning member self-selects out

**Scenario 3:** 1 qualified new member, 7 qualified returning members.
- Problem: the 75% ratio can only be maintained at a committee of size 4, but we require at least 7 committee members. Now what?

**Comment by fboxwala** [comment]
Okay so for scenario 1, what we've been doing up until now seems to be possible outcome 3. We first decide how many returning members there are and (given that there was less than 75%) we filled all the remaining spots with new members. Which leaves the possibility for a qualified new member to not be taken on the committee. If we wanted this to not happen, we should add language giving preference to new members over old members. However, I'm not sure that that's necessary, since I think the 75% ratio covers the problem of developing an "old guard". We could make the ratio something like 60%, to leave more space for new people.  Mostly I'm concerned that if we make this process too specific in the constitution it won't leave room to interpret in special situations.

For scenario 2 and anything similar, I propose that if no one wants to self-select out returning members be referred to the WiCS chair.

For scenario 3, we can change the language to be _"Whenever there are enough qualified new members to allow it, the percent of returning members on the committee should be kept at 75 or less."_

**Comment by fboxwala** [comment]
Bringing this back to people's attention @wics-uw/contributors
