### ISSUE TITLE
Some minor fixes for Policies page

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#128]
- Office policy should be linked there
- Code-of-Conduct link should have spaces, not dashes

Also possibly related: can we get the versioning on the office policy to match that of the Code of Conduct?

**Comment by evykassirer** [comment]
@leafa is working on this I think

**Comment by mxyang42** [comment]
Sure I'll fix both of these

**Comment by evykassirer** [comment]
thanks :D
