### ISSUE TITLE
Posts missing tags

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#129]
- http://wics.uwaterloo.ca/2015/07/intersectionality-workshop/ - should have 'feminism' and 'workshop', not 'academic'
- http://wics.uwaterloo.ca/2015/07/alterconf-toronto-2015/ - should have 'conference' and not 'social'
- http://wics.uwaterloo.ca/2015/06/you-are-not-your-grades/ - should have 'academic' and possibly not social
- http://wics.uwaterloo.ca/2015/05/google-talk/ - should have 'industry'
- http://wics.uwaterloo.ca/2015/03/git-website-workshop/ - should have tag 'open source'

**Comment by evykassirer** [comment]
do you think we could use this beginner friendly issue to introduce a wicsys volunteer to website contribution? is that something we're interested in?

**Comment by ehashman** [comment]
@evykassirer: I think the tag is useful for identifying smaller/easier fixes. I don't think it has to be a wics-sys thing... anyone who is interested can submit a PR, wics-sys or no!

**Comment by anforche** [comment]
@ehashman @evykassirer Could I help in any way? This looks really interesting!

**Comment by fboxwala** [comment]
Hey @anforche! You can go ahead and submit a PR on edits for any of the pages @ehashman mentioned above, I'm sitting on git rn so I can review it pretty fast :)

(If you need any guidance or help message me on fb or /q me on irc, I'm Fatema on OFTC and Freenode!)

**Comment by evykassirer** [comment]
If you're not sure how to get started, or have any questions, please reach out! I'd be glad to help.
I'm glad you're interested and look forward to seeing your pull request :D

**Comment by ehashman** [comment]
I'll also chime in. You can fix this by modifying each of the posts above to add the specified tags, i.e. for the feminism workshop, we [find the corresponding file](https://github.com/wics-uw/website/blame/master/content/S2015/S15-event-intersectionality.md#L4) to the post, and then change the `Tags: academic` line to `Tags: feminism, workshop`. The tags are comma-separated and can contain spaces (for example: the "open source" tag). Rinse and repeat for the rest of the posts listed. If you get stuck, you can contact us on IRC or comment on the issue. If you need any help with git, ditto :)
