### ISSUE TITLE
Fix spacing in CSS for lists

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#161]
For whatever reason, our CSS theming is a bit inconsistent. I commented on how this looks to be a problem in #115. This problem affects pages such as the [Office Policy](http://wics.uwaterloo.ca/office-policy/), and soon, the MUA Summary.

I believe the required fix is to [add some margin to `ul` elements, to match that of `p` elements.](https://github.com/wics-uw/website/pull/115#issuecomment-154839997)

I think the rule change here is beginner-friendly, so please feel free to comment on here if you are interested in working on this and would like to pair or have me mentor.

**Comment by SZain** [comment]
I can see the spacing problem in [Office Policy](http://wics.uwaterloo.ca/office-policy/). 
I would like to fix this.

**Comment by ehashman** [comment]
Okay @SZain, do you understand the comments above? Would screenshots help?

**Comment by SZain** [comment]
Yes i did, but still sending screenshots would definitely help.

**Comment by ehashman** [comment]
I'm a bit busy this week so it will be hard for me to get around to it until maybe next Monday/Tuesday, is that okay?

**Comment by SZain** [comment]
yes that's fine.

**Comment by SZain** [comment]
I was waiting for the screenshots but anyways I have pulled the requests.

**Comment by ehashman** [comment]
Hi @SZain, I haven't seen a pull request. Sorry for not sending that to you; you should feel free to ping people, I just forgot about this issue.

Here is the screenshot:

![screenshot at 2016-03-30 17 17 08](https://cloud.githubusercontent.com/assets/4706131/14157904/423cd0fa-f69b-11e5-8752-0a35a8a9576b.png)

As you can see, spacing between headers and unordered lists is wrong.

**Comment by evykassirer** [comment]
@SZain are you still wanting to work on this?
