### ISSUE TITLE
Someone added Sponsorship and it broke the header

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#173]
Now Tags is on its own line again. Why wasn't this tested? This should be fixed ASAP.

**Comment by fboxwala** [comment]
Am attempting to fix this -- sorry pls dont take my access.

**Comment by ehashman** [comment]
This appears to have been fixed in #174 but now I don't believe it addresses the original ask, which was to visibly display sponsorship information on our website. Hiding it at the bottom of the FAQ likely is going to get you in trouble again. Can you put something in "About" at the very least? And possibly in the footer?

**Comment by fboxwala** [comment]
We can definitely do about and the footer. Is there a way to expand the header?

**Comment by ehashman** [comment]
We could, but it's getting kind of wide. I wonder if we could shrink the spacing between header stuff a tiny bit. Sample past PR: #10

**Comment by fboxwala** [comment]
I can mess around with it tomorrow and try some stuff

**Comment by ehashman** [comment]
Header was unbroken by #174 so this should be closed and other sponsorship stuff should be filed as a separate issue.
