### ISSUE TITLE
Add more people to the Heroku team

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#180]
I would like other people with commit access to be able to hit the "deploy to Heroku" button for the review apps. Please let me know here if you are interested, and we can sync up offline to send you an email invite. Pinging @wics-uw/committers.

**Comment by fboxwala** [comment]
Am interested

**Comment by evykassirer** [comment]
Interested :)

**Comment by ehashman** [comment]
Mentioned on IRC but reiterating here, please message me the email you want your invite to go to.
