### ISSUE TITLE
Add a mention of our library to the website

### ISSUE THREAD

**Issue by arshiamufti** [wics-uw/website#193]
It would list the magazines we subscribe to, any books (electronic or physical) that are available to read. Not sure if this should be a brand new tab on the website or we should link to it in our about page?

**Comment by ehashman** [comment]
It would be cool to add a library section to the office page (I think there's a brief mention of it existing).

**Comment by evykassirer** [comment]
I think having another tab might be too much, but a link from our about page sounds great!! Do we want to use this for the other PR in our git meeting?

**Comment by arshiamufti** [comment]
You mean, have each person attending do a separate PR? Yeah, that would work.

**Comment by evykassirer** [comment]
Yeah, as long as they're both really approachable. How easy do you think this would be for a first PR?

**Comment by ehashman** [comment]
I think this should be split into two PRs:
- [x] One to update the Office section on http://wics.uwaterloo.ca/contact-us/ mentioning we have a library
- [ ] One to add a question to the FAQ about the library's existence (maybe framed as a question for finding resources for learning more about diversity and technology, perhaps?)

**Comment by evykassirer** [comment]
that sounds good to me
@arshiamufti how do you feel about having those as the two PRs, and just updating the committee as an example or while they're working? :)

**Comment by evykassirer** [comment]
@zarinaaa is taking this one, but I can't assign it to her

@ehashman do we need to add her to some list?
