### ISSUE TITLE
Add missing events from the Winter 2016 term

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#195]
Similar to #155, a number of events never made it onto the website for the W16 term. It would be nice if we had a record on the website for posterity's sake, since Facebook events are very ephemeral.

**Comment by evykassirer** [comment]
where could we find a list of events that didn't get to the website?

**Comment by evykassirer** [comment]
would we just go through minutes? or can you think of an easier way

**Comment by evykassirer** [comment]
thanks @fboxwala here's the form with the list of events https://docs.google.com/forms/d/1y4OxANmSI8zAH7-TCB0YO0DPHA15jd-YongcXbaekm0/edit?usp=drive_web

**Comment by ehashman** [comment]
You could also check the calendar and all the historical facebook invites.

**Comment by evykassirer** [comment]
all done 🎉
