### ISSUE TITLE
Add Stephanie Morillo's talk video from W16

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#197]
Similar to #196. Do we have this video available anywhere so I can upload it to the csclub's mirror?

**Comment by evykassirer** [comment]
@annalorimer @fboxwala do you know what the status of the video is?

**Comment by fboxwala** [comment]
Yes it's on the csclub's camera. If you or someone wants, you can go get it and render the video, otherwise I can ask someone in csc to do it? I totally forgot to get it done last term, and I had taken responsibility for it, so sorry about letting it drop.

**Comment by evykassirer** [comment]
If it's easy for you to coordinate, go for it. Otherwise we can have someone from this term committee take it on.

**Comment by fboxwala** [comment]
okay find it here: hfcs:/scratch-hfcs/pj2melan/s16/steph-wics/encodes

**Comment by ehashman** [comment]
Had to recut it from ~00:01:40 to 01:05:04. Recompressing.

**Comment by ehashman** [comment]
Talk is now up: http://mirror.csclub.uwaterloo.ca/wics/stephanie_morillo.mp4
