### ISSUE TITLE
Try out "Ain't CMS"

### ISSUE THREAD

**Issue by ehashman** [wics-uw/website#207]
This may help people with submitting pull requests and keeping the website up to date if they are not super familiar with git: https://aint.io/

Might be a cool thing to research and look into.

**Comment by fboxwala** [comment]
This seems really cool and something to keep an eye on. 

Although, I think learning git is a really important skill for us to be teaching people, and the website has been a great way to teach new committee members and termcoms the basics. I guess I would still want the default to be, fork, branch, commit, PR all over CLI to still be what we default to in onboarding, and then present this as an option later on? It could be veeery useful if we wanted to let community members post blogs posts or something similar though. (or maybe we could somehow incorporate to the medium thing? see gitlab # 55)

**Comment by evykassirer** [comment]
++ to using the website to teach people about git - so far it seems like everyone's benefited a lot from it.

It could be useful to let community members contribute, but I'm not sure if the need for that is really high enough at this point. Most of the people that would blog for us would probably know git or be interested in learning.

Do we want to keep this issue open?

**Comment by ehashman** [comment]
The point is not to enable community members to contribute. The point is to make it easier for committee members to contribute to the website, since despite training, orientations, etc. we still only see a tiny subset of committee members writing website posts.

**Comment by evykassirer** [comment]
I think it's worth the effort to help committee develop the skills to contribute. So far this term is going better than most (I think) and everyone on committee has contributed at least once (though maybe not this term), with more people seeming comfortable picking up more issues. Time will tell more in the next couple weeks (it's a current action on gitlab)

**Comment by evykassirer** [comment]
Committee has been quite involved on GitHub, also a committee member just told me:

> thank you for teaching me git :D
> We're using it for our group project and I'm comfortable with it <3

I think that spending the time to teach git and then encouraging people to take on many issues throughout the term has been incredibly good for the committee.

Would you be comfortable closing this issue now?

**Comment by ehashman** [comment]
Whether or not committee members are better able to get the hang of things, I still think this is something we should take a look at, as it might be super useful down the road. Would prefer to leave this issue open until someone tries it.

**Comment by evykassirer** [comment]
sure, I'll leave it open :)
