### ISSUE TITLE
Add event-running proposal email guidelines

### ISSUE THREAD

**Issue by annalorimer** [wics-uw/website#223]
We want to give people an idea of what sort of information that we're looking for when they want to propose an event. 

Based on the event proposal form that can be found in the drive.

Here: https://docs.google.com/forms/d/1nF1Ssna-j1L9gQQPcTgb8kr81FjKVbprc07cglXYEIk/edit

**Comment by evykassirer** [comment]
Added note: the reason we don't want to use the form is because it doesn't notify us when someone fills it out. We want them to send us an email (with the information in the form)

This would probably be a new page, linked from the volunteer info page?

**Comment by ehashman** [comment]
Suggestions for the form:
- "Time" is too vague. You probably want to consider both "duration" and "time of day."
- "Location" is usually not something that a new event organizer would know or care about; it's the job of the experienced organizers (i.e. you) to figure that out. "Target audience size" is a better ask.
- Same thing with "budget". If the event proposer/organizer knows all these specific details, they probably don't need your help to run the event. Ask instead if they plan on serving food/snacks at the event, if there are any special materials that would need to be purchased, etc.

Finally, I'd suggest you put some thought into the intent of such a form/proposal structure. When I read through this, it appears to me that we are asking people who have fully fleshed out event ideas to ask us to stamp our name on them, and possibly provide some advertising/admin assistance. That doesn't really give people opportunities to propose e.g. their own member talk without knowing all the various organizing details or provide a detailed suggestion for an event they think we should run. I feel like these cases are more common and probably something we want to encourage more. Those that seek to partner with us on events, where they already have the details figured out, don't really need this kind of assistance/guidance.

**Comment by ehashman** [comment]
One more comment: you can turn on email notifications for when a google form is submitted: http://www.labnol.org/internet/email-notification-for-google-docs-forms/5248/

It's under "Tools".

**Comment by evykassirer** [comment]
Seems like this is unnecessary either way then! Feel free to reopen anyone, if you feel otherwise
