### ISSUE TITLE
Update sponsorships page

### ISSUE THREAD

**Issue by arshiamufti** [wics-uw/website#250]
The information on our partnership with BlackBerry on the [sponsorships](http://wics.uwaterloo.ca/sponsorship/) is pretty outdated.

**Comment by evykassirer** [comment]
Information to update:
- the workshops were in F15, W16, and S16 (maybe that could be called the 2015-2016 school year?)
- anywhere it says currently (or something else in future tense), change it to something else
- keep the link to the events we ran with blackberry, but maybe also just state the names of each of them

**Comment by arshiamufti** [comment]
Hm, I don't think we need to need to change the tense. For example, [the machine learning event](http://wics.uwaterloo.ca/2016/06/machine-learning-bb-s16/) (S16) says "this event **is** sponsored by BlackBerry" which was true at the time.

**Comment by evykassirer** [comment]
I mean, on the sponsorship page
