### ISSUE TITLE
Volunteer Sign up form is hard to find

### ISSUE THREAD

**Issue by annalorimer** [wics-uw/website#254]
#### Problem:
- Volunteer sign up form is hard to find
- Currently click paths:
  - About > Form
  - FAQ > About > Form
  - FAQ > Volunteer Opportunities Page > Form

The click paths don't seem that bad, but for some reason it's really hard to find. 
#### Possible solutions:
- Adding a volunteer tab to the nav bar
#### Related Issues:
- #249

**Comment by arshiamufti** [comment]
I feel like it's important enough to add to a navbar but I don't know what we could remove -- the media tab maybe? We could also add it as a link in the footer.

**Comment by evykassirer** [comment]
is there any way to put the media and calendar links at the top of the events page instead of in the nav bar? @fboxwala

**Comment by evykassirer** [comment]
making a new issue for the navbar problem

**Comment by evykassirer** [comment]
this is being handled in the navbar tabs issue, so I'm closing this issue
