### ISSUE TITLE
simplify tags

### ISSUE THREAD

**Issue by evykassirer** [wics-uw/website#255]
There are a bunch of tags for posts on the site. Some are redundant and some are only used on one post and probably won't be used again - let's remove these.

**Comment by arshiamufti** [comment]
Has someone taken this on/does someone want to take it on? I could do this if no one else has the time.

**Comment by fat1996** [comment]
@evykassirer @arshiamufti I'd be willing to take this on. Should I just remove the ones that've been used once?

**Comment by evykassirer** [comment]
that sounds good!

**Comment by annalorimer** [comment]
@fat1996 There's a few tags that have only been used once that we should keep ('Square', 'graphics', 'conference' etc.). Delete the ones you think we don't need and we can comment on that in the PR.

**Comment by fat1996** [comment]
@evykassirer @annalorimer can this be closed?

**Comment by annalorimer** [comment]
@fat1996 I haven't deployed yet but sure.
