### ISSUE TITLE
Reassess Navbar Tabs

### ISSUE THREAD

**Issue by evykassirer** [wics-uw/website#257]
There are too many things we want in the navbar

Volunteering should really be there (#254) but what do we take away? 

Dropdown menus aren't super easy but is an option: https://github.com/getpelican/pelican/issues/1037

Or we could try moving navbar items to links on other pages (e.g. media and calendar as links at the top of the events page) - is this possible?

**Comment by annalorimer** [comment]
Can we rename the issue? It seems like the navbar is broken :/

**Comment by evykassirer** [comment]
True. How's that?

**Comment by annalorimer** [comment]
How about "Reassess Navbar Tabs"?

**Comment by arshiamufti** [comment]
If we're getting rid of the calendar page, we should probably create an issue for that and replacing it with the volunteering tab. Not sure if we've decided that this is the way to go though. Discuss here?

**Comment by evykassirer** [comment]
I definitely think volunteering is most important +1

**Comment by fboxwala** [comment]
+1 Volunteering

**Comment by evykassirer** [comment]
Oo changing this could be a great onboarding task too

**Comment by evykassirer** [comment]
do we want to close this once we put volunteering in?

(that's been assigned to Fatima @fat1996  )

**Comment by evykassirer** [comment]
done with #264
