### ISSUE TITLE
F16 Office Hours

### ISSUE THREAD

**Issue by annalorimer** [wics-uw/website#266]
- Create and event/blog post detailing our office hours for this term

**Comment by evykassirer** [comment]
assigned to Rolina ( @fboxwala  are you able to add her as a contributer to WiCS so I can assign this issue to her?)

**Comment by fboxwala** [comment]
@rolinawu: I've sent you a couple invitations (the should show up in your github notifications) you have to accept them to get added to the team.

**Comment by evykassirer** [comment]
done with #270
