### ISSUE TITLE
Instructions on how to move a commit to a different branch

### ISSUE THREAD

**Issue by arshiamufti** [wics-uw/website#269]
It's often the case that we commit a change and realize we're on the wrong branch (happened in #267). So it would be nice to add documentation on how to move a commit to a different (new or already existing branch)
- before it's pushed
- after it's pushes

**Comment by fboxwala** [comment]
does this happen that often? I don't want to be rewriting all of git's documentation for them. People can a) google when specific problems come up and b) reach out to experienced committee members.

It would be impossible to come up with documentation for every possible scenario that someone has, and we should be encouraging people to do their own research.

**Comment by arshiamufti** [comment]
I think it happens often enough tbh. How about we ask @shivangipatwardhan2018 to look into this and update the documentation? It doesn't have to be a whole text, it could just be a link to a source.

**Comment by annalorimer** [comment]
I agree with Fatema. I honestly have not seen this happen very often and it's important for more experienced people to help out less experienced people. Whether it's directing them to an appropriate resource or going through something step by step.
