### ISSUE TITLE
request for a FAQ

### ISSUE THREAD

**Issue by void-elf** [wics-uw/website#29]
A question I get a lot is: why do you have some women-only events? Maybe we could make a FAQ and include an answer to that that in it?

**Comment by evykassirer** [comment]
Great idea :) we can link to some good articles regarding the issue too, if readers want to investigate further

**Comment by ehashman** [comment]
As briefly discussed earlier, [this is an answer](http://www.reddit.com/r/uwaterloo/comments/2mh3ce/thu_nov_20_530pm_breaking_into_open_source_and/cm4gkra?context=3) to one of those questions.

**Comment by void-elf** [comment]
I really like the reddit comment linked to above (especially since it has an explicit example of a type of event) and we should build upon it when writing the FAQ. I was hoping Geek Feminism would have a page explaining the motivation for women only events, but there isn't one yet.  

"Why found a women geeks group" from here: http://geekfeminism.wikia.com/wiki/Founding_a_women_geeks_group has some good points we could add. 

There are all the things I would have queried a FAQ for if one existed, but instead had to explicitly ask about:
- that we sometimes try to provide food at events for people with gluten sensitivites (but cannot accomodate for extreme gluten sensitivity without some help) and for those who do not consume animal products (people with food sensitivites will often shy away from events if they are worried about being left out)
- we could clarify what "women only" means (I think this is already being discussed elsewhere in this group, but I'm not sure where)
- what the difference is between this wics and the other wics
- maybe: a "how to get involved" thing (there's one on the about page already though, but it took me a while to find it)

**Comment by ehashman** [comment]
These are all fantastic ideas!

@ynasser, please feel free to submit a PR if you are interested. If you just want to keep giving us feedback though, that's also very appreciated! :)

**Comment by SrishtiG** [comment]
:+1:

**Comment by ehashman** [comment]
Addressed by #33, #46.
