### ISSUE TITLE
update FAQ for why we hold women only events

### ISSUE THREAD

**Issue by arshiamufti** [wics-uw/website#297]
- We currently say that we do not publicly advertise women only events, but last semester, committee decided to go ahead and do it.
- It would be nice to give the answer some more detail.

**Comment by arshiamufti** [comment]
Update: the committee will decide during the next meeting if women only events should be publicized from now on, so point 1 can be addressed as per the outcome of that meeting.

**Comment by fboxwala** [comment]
also update: I am working on more in depth explanations right now! I will put up a PR this week.

**Comment by annalorimer** [comment]
I'm confused about "publicly" advertising. We've always advertised on FB and Twitter, which I would characterize as public. The decision was made to start using posters to advertise women-only events.

**Comment by claricen** [comment]
@annalorimer we used to advertise women-only events only in our closed WiCS group on FB so I wouldn't consider that public. On the other hand I'd characterize twitter as public too, but traffic is really low there.

**Comment by annalorimer** [comment]
@claricen aahhh ok thanks 😃
