### ISSUE TITLE
Adding a 'pushing commits' section in the README 

### ISSUE THREAD

**Issue by fat1996** [wics-uw/website#314]
Could we add a small section for how to add commits **after** a pull request has been opened, since the instructions then become "git push origin branch-name" instead of "git push origin HEAD"? I feel this might be helpful, especially after there are changes requested on your PR.

**Comment by annalorimer** [comment]
@fat1996 why did you close this?

**Comment by fat1996** [comment]
@annalorimer I felt this should be added for the wiki that was created for the git workshop instead of the README. I was following the instructions on the wiki, and I felt this was unclear. Should I reopen it? I do have some suggestions for the wiki.

**Comment by annalorimer** [comment]
@fat1996 Makes sense. You just need to leave a note explaining why issues get closed 😃 .
